#!/bin/sh
# Create a repo on GitHub

read -p 'Email: ' EMAIL

docker run --name lastpass-cli --rm -itd mbigras/lastpass-cli
docker exec -it lastpass-cli lpass login $EMAIL

# todo: generate ssh keys

docker run --name hub --rm -itd -v "$(pwd)":/workdir -v ~/.ssh/id_rsa:/root/.ssh/id_rsa mbigras/hub
docker exec hub sh -c "
cat <<EOL >/root/.config/hub
github.com:
- user: mbigras
  oauth_token: $(docker exec lastpass-cli lpass show --notes gh_repo_token)
EOL
hub create $(pwd | xargs -I {} basename '{}')
"
docker rm -f hub lastpass-cli